### ISSUE TITLE
error in CI

### ISSUE THREAD

**Issue by 99002682** [99002526/submition#3]
mkdir build
gcc project_main.c src/calculator_operations.c  -Iinc -o build/Calculator.out.out
project_main.c: In function ‘calculator_menu’:
project_main.c:36:12: warning: unknown escape sequence: '\8'
     printf("\n1. Add\n2. Subtract\n3. Multiply\n4. Divide\n5. Greater\n6. Lesser\n7. Andgate\8. Exit");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/calculator_operations.c: In function ‘andgate’:
src/calculator_operations.c:65:8: error: ‘oparand1’ undeclared (first use in this function); did you mean ‘operand1’?
     if(oparand1 < 0 || operand2 < 0)
        ^~~~~~~~
        operand1
src/calculator_operations.c:65:8: note: each undeclared identifier is reported only once for each function it appears in
make: *** [all] Error 1
Makefile:29: recipe for target 'all' failed
##[error]Process completed with exit code 2.

**Comment by 99002526** [comment]
cleared and build

**Comment by 99002526** [comment]
done
